query GetUsers {
	user_public_view {
		id
		login
		avatarUrl
		firstName
		lastName
		canBeAuditor
		canAccessPlatform
		campus
		githubId
	}
	record_public_view(order_by: { endAt: desc_nulls_last }) {
		userId
		endAt
	}
}
